# simple-dnsd production configuration

listen_address = 0.0.0.0
dns_port = 53
launch = memory
foreground = false
service_user = simple-dnsd
log_file = /var/log/simple-dnsd/simple-dnsd.log
log_level = info
